### ISSUE TITLE
Plugin is not working with Archi4.5

### ISSUE THREAD

**Issue by SilverTiger19** [archi-contribs/snow-import-plugin#4]
Hello,
I used the plugin with Archi 4.4 with no problem. When I upgraded to 4.5, it stopped pulling from SN.
Is there something you can suggest?

**Comment by herve91** [comment]
Hi,

Are you having an "java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter" error ?

If this is the case, this is because the JAXB is not bundled with Java 11 anymore.

I will recompile the plugin with Java 11 as soon as I can, but meanwhile you may launch Archi 4.5 with Java 8 or rollback Archi to 4.4.

Best regards
Hervé

**Comment by herve91** [comment]
will be in next release
